#! /usr/bin/zsh

APP_NAME="org.blender.Blender"
APP_FOLDER="$XDG_RUNTIME_DIR/app/$APP_NAME"
mkdir -p "$APP_FOLDER"

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
fi

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

# A sandboxed dbus filter that 
# makes things a little safer
#
# Bwrap was initially for --die-with-parent,
# but was expanded to fix bugs related to portals
set_up_dbus_proxy() {
  bwrap \
    --new-session \
    --symlink /usr/lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/bin /usr/bin \
    --clearenv \
    --bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --ro-bind-data 3 "/.flatpak-info" \
    --die-with-parent \
    -- \
    xdg-dbus-proxy \
    "$DBUS_SESSION_BUS_ADDRESS" \
    "$APP_FOLDER/bus" \
    --filter \
    --log 3<<EOF
[Application]
name=$APP_NAME
EOF
}

run_app() {
  bwrap \
    --unshare-all \
    --new-session \
    --symlink /usr/lib /lib \
    --symlink /usr/lib64 /lib64 \
    --symlink /usr/bin /bin \
    --symlink /usr/bin /sbin \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /etc /etc \
    --ro-bind /usr/share /usr/share \
    --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --proc /proc \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices /sys/devices \
    --ro-bind /run/dbus /run/dbus \
    --bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --ro-bind "$XDG_RUNTIME_DIR/wayland-1" "$XDG_RUNTIME_DIR/wayland-1" \
    --bind "$XDG_RUNTIME_DIR/doc" "$XDG_RUNTIME_DIR/doc" \
    --bind "$APP_FOLDER/bus" "$XDG_RUNTIME_DIR/bus" \
    --ro-bind "$HOME/Documents/MCprep/build" "$HOME/Documents/MCprep/build" \
    --ro-bind "/media/Blender/Blender C Drive/Worlds for practice/OBJS" "/media/Blender/Blender C Drive/Worlds for practice/OBJS" \
    --ro-bind "$HOME/Documents/Blender/test-builds/blender-4.0.0-alpha+main.69bf9db9a41e-linux.x86_64-release" "$HOME/Documents/Blender/test-builds/blender-4.0.0-alpha+main.69bf9db9a41e-linux.x86_64-release"\
    --dir /tmp \
    --ro-bind "$HOME"/.icons "$HOME"/.icons \
    --ro-bind-data 3 "/.flatpak-info" \
    --setenv XCURSOR_PATH "/run/host/user-share/icons:/run/host/share/icons:$HOME/.icons" \
    --setenv GTK_USE_PORTAL 1 \
    --cap-drop ALL \
    -- \
    "$HOME/Documents/Blender/test-builds/blender-4.0.0-alpha+main.69bf9db9a41e-linux.x86_64-release/blender" \
    3<<EOF
[Application]
name=$APP_NAME
EOF
}

set_up_dbus_proxy &
sleep 0.1
run_app "$@"
