#! /usr/bin/env bash

# This is a sandboxed version of the 
# Vencord installed designed to only 
# access the user installation of the
# Discord Flatpak. Modify to your needs.

# This is a scripted that is converted to base64, which 
# will be converted back to a script in the sandbox
#
# If you wish to view the script, you can simply decode
# this from base64
EMBEDED_SCRIPT="IyEvYmluL3NoCnNldCAtZQoKb3V0ZmlsZT0kKG1rdGVtcCkKdHJhcCAncm0gLWYgIiRvdXRmaWxl
IicgRVhJVAoKZWNobyAiRG93bmxvYWRpbmcgSW5zdGFsbGVyLi4uIgoKc2V0IC0tICJYREdfQ09O
RklHX0hPTUU9JFhER19DT05GSUdfSE9NRSIKCmN1cmwgLXNTIGh0dHBzOi8vZ2l0aHViLmNvbS9W
ZW5kaWNhdGVkL1ZlbmNvcmRJbnN0YWxsZXIvcmVsZWFzZXMvbGF0ZXN0L2Rvd25sb2FkL1ZlbmNv
cmRJbnN0YWxsZXJDbGktTGludXggXAogIC0tb3V0cHV0ICIkb3V0ZmlsZSIgXAogIC0tbG9jYXRp
b24KCmNobW9kICt4ICIkb3V0ZmlsZSIKCiIkb3V0ZmlsZSIK"

APP_NAME="host.local.VencordInstaller"
APP_FOLDER="$XDG_RUNTIME_DIR/app/$APP_NAME"
mkdir -p "$APP_FOLDER"

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
fi

trap 'trap - SIGTERM && kill -- -$$' SIGINT SIGTERM EXIT

# A sandboxed dbus filter that 
# makes things a little safer
#
# Bwrap was initially for --die-with-parent,
# but was expanded to fix bugs related to portals
set_up_dbus_proxy() {
  bwrap \
    --new-session \
    --symlink /usr/lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/bin /usr/bin \
    --clearenv \
    --bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --ro-bind-data 3 "/.flatpak-info" \
    --die-with-parent \
    -- \
    xdg-dbus-proxy \
    "$DBUS_SESSION_BUS_ADDRESS" \
    "$APP_FOLDER/bus" \
    --filter \
    --log 3<<EOF
[Application]
name=$APP_NAME
EOF
}

run_app() {
  bwrap \
    --unshare-all \
    --share-net \
    --symlink /usr/lib /lib \
    --symlink /usr/lib64 /lib64 \
    --symlink /usr/bin /bin \
    --symlink /usr/bin /sbin \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /etc /etc \
    --ro-bind /usr/share /usr/share \
    --dev /dev \
    --proc /proc \
    --ro-bind /sys/dev/char /sys/dev/char \
    --bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
    --bind "$HOME/.local/share/flatpak/app/com.discordapp.Discord" "$HOME/.local/share/flatpak/app/com.discordapp.Discord" \
    --ro-bind "$HOME/.local/bin/vencord-script.sh" "$HOME/.local/bin/vencord-script.sh" \
    --dir /tmp \
    --ro-bind "$HOME"/.icons "$HOME"/.icons \
    --ro-bind-data 3 "/.flatpak-info" \
    -- \
    sh -c "$(base64 -d <<< "$EMBEDED_SCRIPT")" \
    3<<EOF
[Application]
name=$APP_NAME
EOF
}

set_up_dbus_proxy &> /dev/null &
sleep 0.1
run_app "$@"
